# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go install mvdan.cc/garble@latest
builds:
  -
    id: "hq"
    binary: hq
    main: ./cmd/hq/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    gobinary: garble
archives:
  -
    id: hq-binaries
    name_template: "hq-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "hq_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/hq
    maintainer: Michael Paepcke <git@paepcke.de>
    description: hq
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
